#!/bin/bash

FILESIZE=80 #GB
NR_READ_PAGES=128 #nr_pages
NR_THREADS=8
NR_STRIDE=64 #nr_pages
NR_RA_PAGES=1024L #nr_pages

mkdir bin
make -j SIZE=$FILESIZE NR_READ_PAGES=$NR_READ_PAGES NR_THREADS=$NR_THREADS NR_STRIDE=$NR_STRIDE NR_RA_PAGES=$NR_RA_PAGES
