#!/bin/bash

FILESIZE=100 #GB
NR_READ_PAGES=512 #nr_pages
NR_THREADS=4
NR_STRIDE=64 #nr_pages
NR_RA_PAGES=2560L #nr_pages

mkdir bin
make -j SIZE=$FILESIZE NR_READ_PAGES=$NR_READ_PAGES NR_THREADS=$NR_THREADS NR_STRIDE=$NR_STRIDE NR_RA_PAGES=$NR_RA_PAGES
