
all:
	#mpicc -L/usr/local/lib -D SYSTEM -D COLUMBIA -D IO -o MADbench2_io MADbench2.c  -lm -lcfun
	mpicc -L/usr/local/lib -D SYSTEM -D COLUMBIA -D IO -D NO_BUSY_WORK -o MADbench2_io MADbench2.c  -lm
	#mpicc -L/usr/local/lib -D SYSTEM -D COLUMBIA -D IO -o MADbench2_io MADbench2.c  -lm
